version: 2.1
executors:
  deploy:
    parameters:
      dist:
        type: string
      arch:
        type: string
    docker:
    - image: kroniak/ssh-client
    working_directory: /output
    environment:
      DISTRO: << parameters.dist >>
      ARCH: << parameters.arch >>
  rpmbuilder:
    parameters:
      dist:
        type: string
      rpmlint:
        type: integer
        default: 1
      enable_repos:
        type: string
        default: ''
    docker:
    - image: getpagespeed/rpmbuilder:<< parameters.dist >>
    working_directory: /sources
    environment:
      RPMLINT: << parameters.rpmlint >>
      ENABLE_REPOS: << parameters.enable_repos >>
jobs:
  build:
    parameters:
      dist:
        description: The dist tag of OS to build for
        type: string
      enable_repos:
        type: string
        default: ''
      resource_class:
        description: The resource class to use for the build
        type: string
        default: medium
    resource_class: << parameters.resource_class >>
    executor:
      name: rpmbuilder
      dist: << parameters.dist >>
      enable_repos: << parameters.enable_repos >>
    steps:
    - checkout
    - run:
        name: 'Run the build itself: this will do rpmlint and check RPMs existence
          among other things.'
        command: build
    - run:
        name: Check for RPM files and halt if none exist
        command: |-
          if ls /output/*.rpm 1> /dev/null 2>&1; then
            echo "RPM files found. Proceeding with persistence to workspace."
            ls -al /output/*.rpm
          else
            echo "No RPM files found. Halting the job."
            curl --request POST --url https://circleci.com/api/v2/workflow/$CIRCLE_WORKFLOW_ID/cancel --header "Circle-Token: ${CIRCLE_TOKEN}"
            circleci-agent step halt
          fi
    - persist_to_workspace:
        root: /output
        paths:
        - '*.rpm'
  deploy:
    parallelism: 1
    parameters:
      dist:
        description: The dist tag of OS to deploy for
        type: string
      arch:
        description: The architecture to deploy for
        type: string
    executor:
      name: deploy
      dist: << parameters.dist >>
      arch: << parameters.arch >>
    steps:
    - attach_workspace:
        at: /output
    - add_ssh_keys:
        fingerprints:
        - 8c:a4:dd:2c:47:4c:63:aa:90:0b:e0:d6:15:be:87:82
    - run:
        name: Ensure project specific upload directory to avoid deploy collisions
        command: >-
          ssh -o StrictHostKeyChecking=no $GPS_BUILD_USER@$GPS_BUILD_SERVER "mkdir
          -p ~/incoming/${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${ARCH}/${CIRCLE_BRANCH}"
    - run:
        name: Deploy all RPMs to GetPageSpeed repo.
        command: >-
          scp -o StrictHostKeyChecking=no -q -r *.rpm $GPS_BUILD_USER@$GPS_BUILD_SERVER:~/incoming/${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${ARCH}/${CIRCLE_BRANCH}/
    - run:
        name: Trigger Deploy Hook.
        command: >-
          ssh -o StrictHostKeyChecking=no -q $GPS_BUILD_USER@$GPS_BUILD_SERVER "nohup
          ~/scripts/incoming.sh ${CIRCLE_PROJECT_REPONAME}/${DISTRO}/${ARCH}/${CIRCLE_BRANCH}/
          > ~/incoming/$CIRCLE_PROJECT_REPONAME/$DISTRO/${ARCH}/${CIRCLE_BRANCH}/process.log
          2>&1&"
workflows:
  build-deploy-el7-x86_64:
    jobs:
    - build:
        name: build-el7-x86_64
        context: org-global
        dist: el7
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-el7-x86_64
        context: org-global
        dist: el7
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-el7-x86_64
  build-deploy-el8-x86_64:
    jobs:
    - build:
        name: build-el8-x86_64
        context: org-global
        dist: el8
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-el8-x86_64
        context: org-global
        dist: el8
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-el8-x86_64
  build-deploy-el9-x86_64:
    jobs:
    - build:
        name: build-el9-x86_64
        context: org-global
        dist: el9
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-el9-x86_64
        context: org-global
        dist: el9
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-el9-x86_64
  build-deploy-fc41-x86_64:
    jobs:
    - build:
        name: build-fc41-x86_64
        context: org-global
        dist: fc41
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-fc41-x86_64
        context: org-global
        dist: fc41
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-fc41-x86_64
  build-deploy-fc40-x86_64:
    jobs:
    - build:
        name: build-fc40-x86_64
        context: org-global
        dist: fc40
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-fc40-x86_64
        context: org-global
        dist: fc40
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-fc40-x86_64
  build-deploy-amzn2-x86_64:
    jobs:
    - build:
        name: build-amzn2-x86_64
        context: org-global
        dist: amzn2
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-amzn2-x86_64
        context: org-global
        dist: amzn2
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-amzn2-x86_64
  build-deploy-amzn2023-x86_64:
    jobs:
    - build:
        name: build-amzn2023-x86_64
        context: org-global
        dist: amzn2023
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-amzn2023-x86_64
        context: org-global
        dist: amzn2023
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-amzn2023-x86_64
  build-deploy-sles15-x86_64:
    jobs:
    - build:
        name: build-sles15-x86_64
        context: org-global
        dist: sles15
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
    - deploy:
        name: deploy-sles15-x86_64
        context: org-global
        dist: sles15
        arch: x86_64
        filters:
          branches:
            only:
            - main
            - master
            - stable
            - main
        requires:
        - build-sles15-x86_64
